# -*- coding: utf-8 -*-
"""churn_streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oL14ygEg51kyzfZ1ut_ZTdwobwyuujcL
"""

# For streamlit:
# Gender: 1 = Male, 0 = Female
# Country: 0 = France, 1 = Germany, 2 = Spain
# Churn: 1 = Yes, 0 = No
# Scaler is exported as scaler.pkl
# Model is exported as model.pkl
# Order of X: 'gender', 'country', 'age', 'products_number', 'balance', 'active_member'

#!pip install streamlit
#!pip install joblib

import streamlit as st
import joblib
import numpy as np

scaler = joblib.load('scaler.pkl')
model = joblib.load('model.pkl')

st.title('Bank Customer Churn Prediction')

st.divider()

st.write('Please enter the following information to predict whether customer will churn:')

st.divider()

'gender', 'country', 'age', 'products_number', 'balance', 'active_member'

gender = st.selectbox('Gender', ['Male', 'Female'])

country = st.selectbox('Country', ['France', 'Germany', 'Spain'])

age = st.number_input('Age', min_value=18, max_value=100, value=30)

products_number = st.number_input('Products Number', min_value=0, max_value=10, value=2)

balance = st.number_input('Balance', min_value=0.0, max_value=250000.0, value=5000.0)

active_member = st.selectbox('Active Member', ['Yes', 'No'])

st.divider()

predictbutton = st.button("Predict")

if predictbutton:
    gender_selected = 1 if gender == 'Male' else 0
    country_selected = 0 if country == 'France' else 1 if country == 'Germany' else 2
    active_member_selected = 1 if active_member == 'Yes' else 0

    X = [gender_selected, country_selected, age, products_number, balance, active_member_selected]

    X_array = scaler.transform(np.array(X).reshape(1, -1))

    prediction = model.predict(X_array)[0]
    predicted = 'Churned' if prediction == 1 else 'Not Churned'
    st.write('Prediction:', predicted)

else:
    st.write('Please enter all the fields')